package com.currencyconverter.view;

import com.currencyconverter.controller.CurrencyController;
import java.util.*;

public class ConsoleUI {
    private final CurrencyController controller = new CurrencyController();
    private final Scanner scanner = new Scanner(System.in);

    private static final Map<String, String> CURRENCY_NAMES = createCurrencyNames();
    private static Map<String, String> createCurrencyNames() {
        Map<String, String> map = new HashMap<>();
        map.put("FJD", "Fiji Dollar");
        map.put("MXN", "Mexican Peso");
        map.put("SCR", "Seychellois Rupee");
        map.put("TVD", "Tuvaluan Dollar");
        map.put("CDF", "Congolese Franc");
        map.put("BBD", "Barbadian Dollar");
        map.put("GTQ", "Guatemalan Quetzal");
        map.put("CLP", "Chilean Peso");
        map.put("HNL", "Honduran Lempira");
        map.put("UGX", "Ugandan Shilling");
        map.put("ZAR", "South African Rand");
        map.put("TND", "Tunisian Dinar");
        map.put("STN", "São Tomé and Príncipe Dobra");
        map.put("SLE", "Sierra Leonean Leone");
        map.put("BSD", "Bahamian Dollar");
        map.put("SLL", "Sierra Leonean Leone");
        map.put("SDG", "Sudanese Pound");
        map.put("IQD", "Iraqi Dinar");
        map.put("CUP", "Cuban Peso");
        map.put("GMD", "Gambian Dalasi");
        map.put("TWD", "New Taiwan Dollar");
        map.put("RSD", "Serbian Dinar");
        map.put("DOP", "Dominican Peso");
        map.put("KMF", "Comorian Franc");
        map.put("MYR", "Malaysian Ringgit");
        map.put("FKP", "Falkland Islands Pound");
        map.put("XOF", "West African CFA Franc");
        map.put("GEL", "Georgian Lari");
        map.put("UYU", "Uruguayan Peso");
        map.put("MAD", "Moroccan Dirham");
        map.put("CVE", "Cape Verdean Escudo");
        map.put("TOP", "Tongan Paʻanga");
        map.put("AZN", "Azerbaijani Manat");
        map.put("OMR", "Omani Rial");
        map.put("PGK", "Papua New Guinean Kina");
        map.put("KES", "Kenyan Shilling");
        map.put("SEK", "Swedish Krona");
        map.put("BTN", "Bhutanese Ngultrum");
        map.put("UAH", "Ukrainian Hryvnia");
        map.put("GNF", "Guinean Franc");
        map.put("ERN", "Eritrean Nakfa");
        map.put("MZN", "Mozambican Metical");
        map.put("ARS", "Argentine Peso");
        map.put("QAR", "Qatari Riyal");
        map.put("IRR", "Iranian Rial");
        map.put("CNY", "Chinese Yuan");
        map.put("THB", "Thai Baht");
        map.put("UZS", "Uzbekistani Soʻm");
        map.put("XPF", "CFP Franc");
        map.put("MRU", "Mauritanian Ouguiya");
        map.put("BDT", "Bangladeshi Taka");
        map.put("LYD", "Libyan Dinar");
        map.put("BMD", "Bermudian Dollar");
        map.put("KWD", "Kuwaiti Dinar");
        map.put("PHP", "Philippine Peso");
        map.put("RUB", "Russian Ruble");
        map.put("PYG", "Paraguayan Guarani");
        map.put("ISK", "Icelandic Krona");
        map.put("JMD", "Jamaican Dollar");
        map.put("COP", "Colombian Peso");
        map.put("USD", "United States Dollar");
        map.put("MKD", "Macedonian Denar");
        map.put("DZD", "Algerian Dinar");
        map.put("PAB", "Panamanian Balboa");
        map.put("GGP", "Guernsey Pound");
        map.put("SGD", "Singapore Dollar");
        map.put("ETB", "Ethiopian Birr");
        map.put("JEP", "Jersey Pound");
        map.put("KGS", "Kyrgyzstani Som");
        map.put("SOS", "Somali Shilling");
        map.put("VUV", "Vanuatu Vatu");
        map.put("LAK", "Lao Kip");
        map.put("BND", "Brunei Dollar");
        map.put("XAF", "Central African CFA Franc");
        map.put("LRD", "Liberian Dollar");
        map.put("CHF", "Swiss Franc");
        map.put("HRK", "Croatian Kuna");
        map.put("ALL", "Albanian Lek");
        map.put("DJF", "Djiboutian Franc");
        map.put("VES", "Venezuelan Bolívar Soberano");
        map.put("ZMW", "Zambian Kwacha");
        map.put("TZS", "Tanzanian Shilling");
        map.put("VND", "Vietnamese Dong");
        map.put("AUD", "Australian Dollar");
        map.put("ILS", "Israeli New Shekel");
        map.put("GHS", "Ghanaian Cedi");
        map.put("GYD", "Guyanese Dollar");
        map.put("BOB", "Bolivian Boliviano");
        map.put("KHR", "Cambodian Riel");
        map.put("MDL", "Moldovan Leu");
        map.put("IDR", "Indonesian Rupiah");
        map.put("KYD", "Cayman Islands Dollar");
        map.put("AMD", "Armenian Dram");
        map.put("BWP", "Botswana Pula");
        map.put("SHP", "Saint Helena Pound");
        map.put("TRY", "Turkish Lira");
        map.put("LBP", "Lebanese Pound");
        map.put("TJS", "Tajikistani Somoni");
        map.put("JOD", "Jordanian Dinar");
        map.put("AED", "United Arab Emirates Dirham");
        map.put("HKD", "Hong Kong Dollar");
        map.put("RWF", "Rwandan Franc");
        map.put("EUR", "Euro");
        map.put("FOK", "Faroese Króna");
        map.put("LSL", "Lesotho Loti");
        map.put("DKK", "Danish Krone");
        map.put("CAD", "Canadian Dollar");
        map.put("KID", "Kiribati Dollar");
        map.put("BGN", "Bulgarian Lev");
        map.put("MMK", "Burmese Kyat");
        map.put("MUR", "Mauritian Rupee");
        map.put("NOK", "Norwegian Krone");
        map.put("SYP", "Syrian Pound");
        map.put("IMP", "Isle of Man Pound");
        map.put("ZWL", "Zimbabwean Dollar");
        map.put("GIP", "Gibraltar Pound");
        map.put("RON", "Romanian Leu");
        map.put("LKR", "Sri Lankan Rupee");
        map.put("NGN", "Nigerian Naira");
        map.put("CRC", "Costa Rican Colón");
        map.put("CZK", "Czech Koruna");
        map.put("PKR", "Pakistani Rupee");
        map.put("XCD", "East Caribbean Dollar");
        map.put("ANG", "Netherlands Antillean Guilder");
        map.put("HTG", "Haitian Gourde");
        map.put("XCG", "Unrecognized Currency");
        map.put("BHD", "Bahraini Dinar");
        map.put("KZT", "Kazakhstani Tenge");
        map.put("SRD", "Surinamese Dollar");
        map.put("SZL", "Swazi Lilangeni");
        map.put("SAR", "Saudi Riyal");
        map.put("TTD", "Trinidad and Tobago Dollar");
        map.put("YER", "Yemeni Rial");
        map.put("MVR", "Maldivian Rufiyaa");
        map.put("AFN", "Afghan Afghani");
        map.put("INR", "Indian Rupee");
        map.put("AWG", "Aruban Florin");
        map.put("KRW", "South Korean Won");
        map.put("NPR", "Nepalese Rupee");
        map.put("JPY", "Japanese Yen");
        map.put("MNT", "Mongolian Tögrög");
        map.put("AOA", "Angolan Kwanza");
        map.put("PLN", "Polish Złoty");
        map.put("GBP", "British Pound Sterling");
        map.put("SBD", "Solomon Islands Dollar");
        map.put("BYN", "Belarusian Ruble");
        map.put("HUF", "Hungarian Forint");
        map.put("BIF", "Burundian Franc");
        map.put("MWK", "Malawian Kwacha");
        map.put("MGA", "Malagasy Ariary");
        map.put("XDR", "IMF Special Drawing Rights");
        map.put("BZD", "Belize Dollar");
        map.put("BAM", "Bosnia-Herzegovina Convertible Mark");
        map.put("EGP", "Egyptian Pound");
        map.put("MOP", "Macanese Pataca");
        map.put("NAD", "Namibian Dollar");
        map.put("SSP", "South Sudanese Pound");
        map.put("NIO", "Nicaraguan Córdoba");
        map.put("PEN", "Peruvian Sol");
        map.put("NZD", "New Zealand Dollar");
        map.put("WST", "Samoan Tala");
        map.put("TMT", "Turkmenistan Manat");
        map.put("BRL", "Brazilian Real");
        return map;
    }

    public void start() {
        try {
            System.out.println("Welcome to Currency Converter!");
            System.out.print("Enter base currency (e.g., USD): ");
            String base = scanner.nextLine().trim().toUpperCase();
            Map<String, Double> rates = controller.getAvailableRates(base);
            System.out.println("Available target currencies:");
            for (String code : rates.keySet()) {
                String name = CURRENCY_NAMES.getOrDefault(code, "Unknown");
                System.out.printf("%s - %s\n", code, name);
            }
            System.out.print("Enter target currency: ");
            String target = scanner.nextLine().trim().toUpperCase();
            if (!rates.containsKey(target)) {
                System.out.println("Invalid target currency.");
                return;
            }
            System.out.print("Enter amount to convert: ");
            double amount = Double.parseDouble(scanner.nextLine().trim());
            double result = controller.convertCurrency(base, target, amount);
            System.out.printf("%f %s = %f %s\n", amount, base, result, target);
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }
}
